apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==         # base64 for 'root'
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=     # base64 for 'password'
